name: YCTI Auto DevOps CI
on:
  push:
     branches:
        - main
        - student*
jobs:
  build:

     runs-on: ubuntu-latest

     steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Show Branch Name
          run: echo "CI running for branch ${{ github.ref_name }}"

        - name: Build Simulation
          run: |
            echo "YCTI DevOps Internship CI Pipeline"
            echo "Student Branch: ${{ github.ref_name }}"
            echo "Build Completed Successfully"
